<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Direction;
use Carbon\Carbon;
class DirectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
   public function run()
    {
         Direction::create([
       	    
       	    'name'=> 'Поставка оборудования',
       	    'director'=>'Яковлев Ким Иванович',
       	    'opisanie'=>"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged"
           
           ])->employees()->createMany([
               
            ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
             'phonenum'=> '+998931869789',
             'gender'=>'Мужчина',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
             
          ]);
           Direction::create([
       	    
       	    'name'=> 'Информационные технологии',
       	    'director'=>'Егоров Жигер Виталиевич',
       	    'opisanie'=>"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged"
           
           ])->employees()->createMany([
               
            ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'dismissed'=>1,
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),
             'exitdate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
             
             
          ]);
           Direction::create([
       	    
       	    'name'=> 'Производство',
       	    'director'=>'Миклашевский Бронислав Ярославович',
       	    'opisanie'=>"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged"
           
           ])->employees()->createMany([
               
            ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'dismissed'=>1,
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),
             'exitdate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'dismissed'=>1,
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),
             'exitdate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Моисеенко',
              'name'=> 'Радислав',
              'patronymic'=>'Ярославович',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Техник',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Механик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Лебедев',
              'name'=> 'Устин',
              'patronymic'=>'Васильевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
         ['surname'=> 'Батиров',
              'name'=> 'Мурат',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
        ['surname'=> 'Маматов',
              'name'=> 'Нурбек',
              'patronymic'=>'Сайдиллаевич',
             'birthdate' =>Carbon::create('1989', '01', '01'),
              'gender'=>'Мужчина',
             'phonenum'=> '+998931869789',
             'passportnum'=>'AA1234567',
             'position'=>'Кабельщик',
             'wages'=>5000000,
             'comedate'=>Carbon::create('2020', '01', '01'),

        ],
             
             
          ]);
      


       
    }
}
